version: "3.7"
services:
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
  redisAdmin:
    image: erikdubbelboer/phpredisadmin
    ports:
      - "8080:80"
    environment:
      REDIS_1_HOST: redis
      REDIS_1_PORT: 6379
      REDIS_1_NAME: localhost